import { Link, useNavigate } from 'react-router-dom'
import { useState } from 'react'
import { useAuth } from '../context/AuthContext'
import { apiErrorMessage } from '../services/api'

export default function RegisterPage() {
  const { register } = useAuth(); const navigate = useNavigate(); const [form, setForm] = useState({ name: '', email: '', password: '', confirmPassword: '', role: 'student', skills: '' }); const [error, setError] = useState(''); const [loading, setLoading] = useState(false)
  const submit = async (event) => { event.preventDefault(); setLoading(true); setError(''); try { const user = await register(form); navigate(user.role === 'student' ? '/dashboard' : `/${user.role}`, { replace: true }) } catch (err) { setError(apiErrorMessage(err, 'Unable to create your account right now.')) } finally { setLoading(false) } }
  return <main className="auth-page"><div className="auth-aside"><Link className="brand light" to="/">SkillUp</Link><div><p className="kicker light-kicker">Start with intent</p><h1>Your next opportunity<br />starts here.</h1><p>Build a bridge between what you are learning and where you want to go.</p></div><span className="aside-foot">A focused space for emerging talent</span></div><section className="auth-card register-card"><div className="auth-card-header"><span className="mobile-brand">SkillUp</span><p className="kicker">Join the platform</p><h2>Create your account</h2><p>Tell us a little about how you will use SkillUp.</p></div><form onSubmit={submit} className="auth-form">{error && <div className="form-error" role="alert">{error}</div>}<label>Full name<input value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} placeholder="Your name" required /></label><label>Email address<input type="email" autoComplete="email" value={form.email} onChange={(event) => setForm({ ...form, email: event.target.value })} placeholder="you@example.com" required /></label><div className="form-row"><label>Password<input type="password" autoComplete="new-password" value={form.password} onChange={(event) => setForm({ ...form, password: event.target.value })} placeholder="At least 6 characters" required minLength="6" /></label><label>Confirm password<input type="password" autoComplete="new-password" value={form.confirmPassword} onChange={(event) => setForm({ ...form, confirmPassword: event.target.value })} placeholder="Repeat password" required /></label></div><label>Account type<select value={form.role} onChange={(event) => setForm({ ...form, role: event.target.value })}><option value="student">Student</option><option value="mentor">Institute mentor</option><option value="recruiter">Industry recruiter</option></select></label>{form.role === 'student' && <label>Skills <input value={form.skills} onChange={(event) => setForm({ ...form, skills: event.target.value })} placeholder="React, SQL, Figma" /><span className="field-hint">Separate skills with commas. You can edit this later.</span></label>}<button className="primary-button full-width" disabled={loading}>{loading ? 'Creating account...' : 'Create account'}</button></form><p className="auth-switch">Already have an account? <Link to="/login">Sign in</Link></p></section></main>
}
